Repository Quaran-Team/client-Amazin, pull requests merged in 2020-08, with the labels that each got.

#88 Bugfix classrename
  src/components/RatingSummary/badChartmock.js
  src/components/RatingSummary/badStar.js
  src/components/RatingSummary/chartMock.css
  src/components/RatingSummary/goodChartMock.js
  src/components/RatingSummary/goodStar.js
  src/components/RatingSummary/highChartMock.js
  src/components/RatingSummary/highStar.js
  src/components/RatingSummary/lowChartMock.js
  src/components/RatingSummary/lowStar.js
  src/components/RatingSummary/midChartMock.js
  src/components/RatingSummary/midStar.js
  src/components/RatingSummary/stars.css
Labels: chore

#92 Feature/css pv
  package-lock.json
  src/components/ComparisonGrid/ComparisonItem.jsx
  src/components/PrimaryPage.jsx
  src/components/primarypage.css
  src/components/productVariant/Product.jsx
  src/components/productVariant/product.css
  src/components/productVariant/variant-Components/Availability.jsx
  src/components/productVariant/variant-Components/Details.jsx
  src/components/productVariant/variant-Components/Header.jsx
  src/components/productVariant/variant-Components/Sponsered.jsx
  src/components/productVariant/variant-Components/Sponsored.jsx
Labels: feature

#121 Feature/dynamicstars
  package-lock.json
  package.json
  src/components/App.jsx
  src/components/PrimaryPage.jsx
  src/components/RatingSummary/Appples.js
  src/components/RatingSummary/dynamicStar.jsx
  src/components/RatingSummary/dynamicStarChart.jsx
  src/components/TopBar/Cart.js
  src/components/TopBar/Flag.js
  src/components/TopBar/Logo.js
  src/components/TopBar/Menu.js
  src/components/TopBar/Prime.js
  src/components/TopBar/Returns.js
  src/components/TopBar/SearchBar.jsx
  src/components/TopBar/SignIn.js
  src/components/TopBar/TopBar.js
  src/components/TopBar/flagUs.png
  src/components/TopBar/topbar.css
  src/components/TopBar/usFlag.JPG
Labels: feature

#123 Feature/topbar
  public/images/preFoot.JPG
  src/components/App.jsx
  src/components/RatingSummary/dynamicStarChart.jsx
  src/components/TopBar/Prime.js
  src/components/TopBar/TopBar.js
  src/components/TopBar/WorkinMenu.js
  src/components/TopBar/menu.css
Labels: enhancement, feature

#134 it is unbroken
  src/components/App.jsx
  src/components/Footer/Bluefoot.js
  src/components/Footer/BottomLine.js
  src/components/Footer/Footer.js
  src/components/Footer/Prefoot.js
  src/components/Footer/footer.css
  src/components/PrimaryPage.jsx
  src/components/SecondTopLine/BestSellers.js
  src/components/SecondTopLine/BlueSecondTop.css
  src/components/SecondTopLine/BlueSecondTopline.js
  src/components/SecondTopLine/CustomerService.js
  src/components/SecondTopLine/Deals.js
  src/components/SecondTopLine/Foods.js
  src/components/SecondTopLine/Gift.js
  src/components/SecondTopLine/GiftCards.js
  src/components/SecondTopLine/Location.js
  src/components/SecondTopLine/NewReleases.js
  src/components/SecondTopLine/Registry.js
  src/components/SecondTopLine/School.js
  src/components/SecondTopLine/Shipping.js
  tests/blBlueTopBar.spec.js
  tests/footertest.spec.js
  tests/topbartest.spec.js
Labels: bug, chore

#136 Chore/fixthereadme
  README.md
  amazinscreen.JPG
Labels: chore, documentation

#137 Chore/fixthereadme
  README.md
Labels: chore, documentation

#141 Feature/topfooter
  README.md
  src/components/Footer/Bluefoot.js
  src/components/Footer/footer.css
  src/components/SecondTopLine/BlueSecondTop.css
  src/components/TopBar/TopBar.js
  src/components/TopBar/flagUs.png
  src/components/TopBar/usFlag.JPG
Labels: documentation, enhancement, feature

#142 Updates
  README.md
  src/components/PrimaryPage.jsx
Labels: documentation

#144 updated tests
  README.md
  src/components/App.jsx
  src/components/RatingSummary/dynamicStar.jsx
  src/components/RatingSummary/lowStar.js
  tests/__snapshots__/customerReviews.spec.js.snap
  tests/app.spec.js
  tests/blBlueTopBar.spec.js
  tests/blStars1.spec.js
  tests/blStars2.spec.js
  tests/blStars3.spec.js
  tests/blStars4.spec.js
  tests/blStars5.spec.js
  tests/chartBad.spec.js
  tests/chartGood.spec.js
  tests/chartHigh.spec.js
  tests/chartLow.spec.js
  tests/chartMid.spec.js
  tests/photogallery.spec.js
  tests/topbartest.spec.js
Labels: chore
