Repository Quaran-Team/client-Amazin, pull requests merged in 2020-07, with the labels that each got.

#39 initialized react
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/components/App.js
  src/index.html
  src/index.js
  webpack.config.js
Labels: chore

#67 Brianstestbranch
  jest.config.js
  jest.config.json
  package-lock.json
  package.json
  src/components/RatingSummary/Appples.js
  src/components/RatingSummary/badChartmock.js
  src/components/RatingSummary/badStar.js
  src/components/RatingSummary/chartMock.css
  src/components/RatingSummary/goodChartMock.js
  src/components/RatingSummary/goodStar.js
  src/components/RatingSummary/highChartMock.js
  src/components/RatingSummary/highStar.js
  src/components/RatingSummary/lowChartMock.js
  src/components/RatingSummary/lowStar.js
  src/components/RatingSummary/midChartMock.js
  src/components/RatingSummary/midStar.js
  src/config/CSSStub.js
  tests/__snapshots__/blStars1.spec.js.snap
  tests/__snapshots__/blStars2.spec.js.snap
  tests/__snapshots__/blStars3.spec.js.snap
  tests/__snapshots__/blStars4.spec.js.snap
  tests/__snapshots__/blStars5.spec.js.snap
  tests/blStars1.spec.js
  tests/blStars2.spec.js
  tests/blStars3.spec.js
  tests/blStars4.spec.js
  tests/blStars5.spec.js
  webpack.config.js
Labels: bug

#69 Brianstestbranch
  package-lock.json
  package.json
  src/components/RatingSummary/Appples.js
  src/components/RatingSummary/badChartmock.js
  src/components/RatingSummary/badStar.js
  src/components/RatingSummary/chartMock.css
  src/components/RatingSummary/goodChartMock.js
  src/components/RatingSummary/goodStar.js
  src/components/RatingSummary/highChartMock.js
  src/components/RatingSummary/highStar.js
  src/components/RatingSummary/lowChartMock.js
  src/components/RatingSummary/lowStar.js
  src/components/RatingSummary/midChartMock.js
  src/components/RatingSummary/midStar.js
  src/components/RatingSummary/stars.css
  src/components/productVariant/variant-Components/Header.jsx
  src/setupTests.js
  tests/blStars1.spec.js
  tests/blStars2.spec.js
  tests/blStars3.spec.js
  tests/blStars4.spec.js
  tests/blStars5.spec.js
  tests/chartBad.spec.js
  tests/chartGood.spec.js
  tests/chartHigh.spec.js
  tests/chartLow.spec.js
  tests/chartMid.spec.js
Labels: enhancement
